// Generated by https://quicktype.io

export interface Property {
    data: Data;
}

export interface Data {
    listProperties: ListProperty[];
}

export interface ListProperty {
    property_id:   number;
    property_name: string;
}
