// Generated by https://quicktype.io

export interface Room {
    data: Data;
}

export interface Data {
    listRoomRates: ListRoomRate[];
}

export interface ListRoomRate {
    basic_nightly_rate: number;
    date:               string;
    room_rate_id:       number;
}
